### ISSUE TITLE
Breadcrumbs not showing as expected product details page

### ISSUE THREAD

**Issue by gjportegies** [SnowdogApps/magento2-alpaca-theme#104]
Magento CE 2.2.6
Clean Alpaca Theme

Breadcrumbs are not displaying as expected on the product detail page. Since Magento CE 2.2.4 there is a separate breadcrumbs file in Magento_Catalog/templates/product/breadcrumbs.phtml. We probably need to override this file with our own styled version. See this issue https://github.com/magento/magento2/issues/15490

<img width="1351" alt="schermafbeelding 2018-11-28 om 10 27 01" src="https://user-images.githubusercontent.com/6707410/49142457-2406bd00-f2f9-11e8-8d0a-b5f2b70e285e.png">

**Comment by robwozniak** [comment]
@gjportegies  you're right, this is because (since mg 2.2.4) way of rendering breadcrumbs on product page slightly changed. I've added updated breadcrumbs template, also other related templates were updated.
