### ISSUE TITLE
Menu module does not appear in Magento 2.3.0 

### ISSUE THREAD

**Issue by koralgolek** [SnowdogApps/magento2-alpaca-theme#117]
After fresh installation of Magento 2.3.0 and magento2-alpaca-theme I created new menu in admin panel. Unfortunately menu doesn't appear on the home page.

![image](https://user-images.githubusercontent.com/33431714/52410825-f3ea5000-2ad9-11e9-8386-2576ff483b35.png)

**Comment by koralgolek** [comment]
I forgot to set proper Identifier...

**Comment by VivekShingala** [comment]
Hi @pawelcit 

Could you please explain how did you set the menu and homepage? Thanks

**Comment by pawelcit** [comment]
Hi @VivekShingala 

Unfortunately I don't remeber exactly but I hope it will help. In admin panel in Content --> Menus I created new Menu with Indentifier: **main-desktop** and Menu Main CSS Class: **mega-menu** and added few Nodes.
