### ISSUE TITLE
Configurable swatches do not change price

### ISSUE THREAD

**Issue by razza12** [SnowdogApps/magento2-alpaca-theme#121]
On Magento 2.3.0, when configurable products are set up with different option prices, they do not seem to be reloaded in the Catalog List upon selecting a swatch option

**Comment by szafran89** [comment]
Thanks for the report, we will check it.
@Aekal internal ticket dev-50475

**Comment by Aekal** [comment]
@razza12 Fixed in develop, we'll prepare 1.2.0 release soon
