### ISSUE TITLE
Missing images in related products

### ISSUE THREAD

**Issue by koralgolek** [SnowdogApps/magento2-alpaca-theme#122]
On Mangeto 2.3 on the  product page, related products' images do not appear. Probably there is a problem with styles.

**Comment by szafran89** [comment]
Thanks for the report, we will check it.
Internal ticket dev-50641

**Comment by Aekal** [comment]
@koralgolek Ready in v1.2.0, you can see related products here https://alpaca-ce-demo.snowdog.pro/primo-endurance-tank.html
