### ISSUE TITLE
Gulp generates css files without "min" in name if Minify CSS files is enabled

### ISSUE THREAD

**Issue by koralgolek** [SnowdogApps/magento2-alpaca-theme#129]
I am not sure if it is a bug but, in developer mode there is a mode in Stores-> Settings-> Configuration-> Advanced -> Developer-> CSS Settings: Minify CSS Files. When it is enabled then Magento expects  i.e. (pub/static/frontend/Snowdog/alpaca/pl_PL/Magento_Checkout/) checkout.min.css instead of checkout.css or (pub/static/frontend/Snowdog/alpaca/pl_PL/css) styles.min.css instead of styles.css. 

I worked around it making the copy of existing file with the correct name with ".min.".

**Comment by Januszpl** [comment]
run `gulp` command in tools dir and you will see extra info about commands

```
    * styles - Use this task to manually trigger styles processing pipeline.    * --theme name - Process single theme.
        * --disableMaps - Disable inline source maps generation.
        * --prod - Production output - minifies styles and add .min sufix.
        * --ci - Enable throwing errors. Useful in CI/CD pipelines.
```

so running `gulp styles --prod` will generate files with ".min"

**Comment by Januszpl** [comment]
Feel free to add comment if this will be still an issue for you. For now closing it.
