### ISSUE TITLE
Escaping php variables in templates

### ISSUE THREAD

**Issue by Januszpl** [SnowdogApps/magento2-alpaca-theme#131]
There are places were we use in html attr `escapeHtml` instead of escapeQuotes (M 2.1) or escapeHtmlAttr (> m2.2) or where we don't use any escape methods. The same for url etc.

However which method should be used vary depending on Magento version but I think we should support from some release > M2.2 and keep support for M2.1 on some release branch.

What method to use and when explained here:
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-security.html

For M 2.1: https://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-security.html

**Comment by Igloczek** [comment]
Internal ticket - DEV-67311
