### ISSUE TITLE
Hardcoded text without translation method inside .html files

### ISSUE THREAD

**Issue by Januszpl** [SnowdogApps/magento2-alpaca-theme#135]
In .html files we have hardcoded text for example for aria-label etc attributes. 
[/Magento_Checkout/web/template/minicart/item/default.html](https://github.com/SnowdogApps/magento2-alpaca-theme/blob/ab70058eb1a1e650f6c6134110117315de9ec386/Magento_Checkout/web/template/minicart/item/default.html#L135-L139)

```
<a
    data-bind="attr: {href: configure_url, title: $t('Edit item')}"
    class="button button--icon minicart-product__button"
     aria-label="edit product in your shopping cart"
>
```

We should move aria-label to `data-bind="attr: {[here]}` and use $t method if available in specific file.

**Comment by Igloczek** [comment]
Internal ticket - DEV-67310

**Comment by anqaka** [comment]
issue not exist in 2.0
