### ISSUE TITLE
Empty category collection when using elasticsearch.

### ISSUE THREAD

**Issue by dimitar-ivanov-tryzens** [SnowdogApps/magento2-alpaca-theme#153]
Magento 2.3.3 Commerce, Alpaca theme 1.3.1, Elasticsearch 6, Magento Sample data installed, visiting any category page will results in the message - "We can't find products matching the selection." shown in the products list space. The same as if no products are available.
With the same product setup but with mysql as a search engine products load successfully.
I have tracked down the issue to:
```
<!-- vendor/snowdog/theme-frontend-alpaca/Magento_Catalog/layout/catalog_category_view.xml:21 -->
        <!-- Moved blocks -->
        <move element="div.sidebar.main" destination="columns" before="main"/>
```
Moving Layered navigation before the product list causes the empty product collection. If I comment this line the product collection loads fine.

**Comment by AJMaxwell** [comment]
I am having the same issue. You can work around it by navigating to to `Stores > Settings > Configuration > Catalog > Catalog > Catalog Search` and changing "Search Engine" to *MySQL*.

Still trying to figure out exactly why this is happening.

**Comment by AJMaxwell** [comment]
I am having the same issue. You can work around it by navigating to to `Stores > Settings > Configuration > Catalog > Catalog > Catalog Search` and changing "Search Engine" to *MySQL*.

Still trying to figure out exactly why this is happening.

**Comment by AJMaxwell** [comment]
I am having the same issue. Still trying to figure out exactly why this is happening.

You can work around it by navigating to to `Stores > Settings > Configuration > Catalog > Catalog > Catalog Search` and changing "Search Engine" to *MySQL*.

**Comment by Igloczek** [comment]
Let sa that Alpaca 1.x does not support Elasticsearch based catalog.

It's going to change in the incoming 2.0 release.
