### ISSUE TITLE
Checkout cart actions html issue 

### ISSUE THREAD

**Issue by ahentea** [SnowdogApps/magento2-alpaca-theme#158]
In the following file:
Magento_Checkout/templates/cart/item/renderer/actions/remove.phtml
On line 1 there is a button tag opened and at the end on line 9 there is an anchor tag closed. 
The anchor closing tag should be changed for a button closing tag.
![remove_phtml](https://user-images.githubusercontent.com/13118637/66553860-37ef9200-eb4c-11e9-87b6-7ec8a8a0a52b.jpg)

Thanks!

**Comment by Igloczek** [comment]
Hi @ahentea, thanks for the report.
Could you please prepare a fix for this issue and submit pull request? We will be more than happy to merge it.
