### ISSUE TITLE
Possible to deactivate Snowdog_Menu?

### ISSUE THREAD

**Issue by jg-development** [SnowdogApps/magento2-alpaca-theme#168]
Is it possible to disable the snowdog menu?
We are using an import based menu with the standard magento menu.
If I disable the Snowdog_Menu I get the following error:
Fatal error: Uncaught Error: Cannot instantiate interface Snowdog\Menu\Api\MenuRepositoryInterface in...
In short:
I want to use the normal Magento Menu
Thx in advance

**Comment by Igloczek** [comment]
You need to remove the related blocks from layout - https://github.com/SnowdogApps/magento2-alpaca-theme/blob/master/Magento_Theme/layout/default.xml#L41-L51

**Comment by Januszpl** [comment]
I'm closing issue. If you will need some more details please feel free to reopen.
