### ISSUE TITLE
Do I absolutely need Node.js v12?

### ISSUE THREAD

**Issue by kennylawrence** [SnowdogApps/magento2-alpaca-theme#173]
Hello, I am trying to use your alpaca theme because I am frustrated with Magento's frontend scheme using LESS. I don't have a problem with LESS, but the structure is confusing.

I am at the step "Install Frontools dependecies and setup config files cd vendor/snowdog/frontools && yarn && gulp setup"

Yarn barfs on my node.js version 10... I am hosted at Nexcess so don't have access to modify the server, though I can request version 12... is this necessary or can I just change the version requirement in /vendor/snowdog/frontools/.node-version  ?

**Comment by Igloczek** [comment]
It should work on 10.x too, we limit it to the current LTS version out of convenience coming with supporting just one thing at the time. 

Although, you need to change it in `engines` property in `package.json`, `.node-version` file is for [AVN](https://github.com/wbyoung/avn).

**Comment by kennylawrence** [comment]
I got this error:

error eslint@6.6.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "10.10.0"

is that going to be alright? I am not sure what eslint is for..

**Comment by Igloczek** [comment]
You have a few options:
1. (Best) Ask hosting provider to update to more recent Node.js version than something that was released in September 2018 (at least higher than 10.13, because that's was previous LTS version).
2. (Should be safe) Use NPM instead of Yarn, it will not yell at you about Node.js version, because it doesn't give a shit about expected Node.js version.
3. (It might break the tools) Remove `yarn.lock` and run `yarn` to fetch all dependencies from scratch in their latest versions within the ranges from `package.json`

**Comment by kennylawrence** [comment]
Thanks - I have requested #1 with the host, we'll see.. Meanwhile, could you let me know what I should do differently in the instructions to use npm instead of yarn?

**Comment by Igloczek** [comment]
`yarn` -> `npm install`
`yarn sometask` -> `npm run sometask`

For more, check out the README or google it, it's not a specific thing to these tools -> https://github.com/SnowdogApps/magento2-frontools

**Comment by kennylawrence** [comment]
oh, I see - they use the same package.json. Got it, thanks!

**Comment by kennylawrence** [comment]
npm seems to have installed things OK.. there were a few packages that needed to be installed independently/manually, which I have not yet - I think one was related to lint.

I configured the theme to the alpaca one and ran "gulp styles && gulp babel && gulp svg". Loading the home page results in a blank white page - actually there is no html source.

Next if I switch to the blank theme and flush cache, it loads. Switching back to the alpaca theme and flushing cache results in no html source again. This is using the "clean" alpaca theme (no parent) configuration in the theme.json file. Have I missed something?

**Comment by kennylawrence** [comment]
It's an error 500 I should say..

**Comment by kennylawrence** [comment]
I needed to do a "bin/magento setup:upgrade"  ! should add this to the instructions. Found this in the instructions for the snowdog blank theme. :)

**Comment by Igloczek** [comment]
It's not related to this or any other theme, but it's required while adding anything new to the Magento 2.
