### ISSUE TITLE
Could not find a matching version of package snowdog/alpaca-packages

### ISSUE THREAD

**Issue by lumay** [SnowdogApps/magento2-alpaca-theme#208]
Hello, I've had the following message when trying to install with composer :
Could not find a matching version of package snowdog/alpaca-packages
Did I miss something?

**Comment by santibm** [comment]
Same here

**Comment by gimmig** [comment]
> Same here
> This one seems to work: composer require snowdog/module-alpaca-packages

You might also change it in the readme
