### ISSUE TITLE
Move footer links to cms menu

### ISSUE THREAD

**Issue by anqaka** [SnowdogApps/magento2-alpaca-theme#28]
Footer links move from phtml (`vendor/snowdog/theme-frontend-alpaca/Magento_Theme/templates/footer/footer-links.phtml`) to cms menu (`snowdog/module-menu`) after resolving [issue concerning overwriting templates by menu id](https://github.com/SnowdogApps/magento2-menu/issues/27)

**Comment by szafran89** [comment]
@niemaco IMO it's good first pick ;)
