### ISSUE TITLE
Magento 2.3.5-p2 changes

### ISSUE THREAD

**Issue by peterjaap** [SnowdogApps/magento2-alpaca-theme#314]
Here's a change in [Magento_Checkout/web/template/summary/item/details.html](https://github.com/SnowdogApps/magento2-alpaca-theme/blob/master/Magento_Checkout/web/template/summary/item/details.html) in Magento 2.3.5-p2 that hasn't been reflected in Alpaca yet; https://github.com/magento/magento2/commit/9436781734e47c83e96977fa770d255217680d5e#diff-900f4e598cbd03ef3b68cbc13ee41ff1

Here's another change in [Magento_Wishlist/templates/sidebar.phtml](https://github.com/SnowdogApps/magento2-alpaca-theme/blob/master/Magento_Wishlist/templates/sidebar.phtml) where they introduced a ViewModel instead of a Helper, which isn't reflected in Alpaca yet; https://github.com/magento/magento2/commit/9436781734e47c83e96977fa770d255217680d5e#diff-b250b4d7486ee5cf4304855743306545

**Comment by peterjaap** [comment]
It looks like stuff will just keep working without these changes, but they might introduce security issues.

**Comment by Januszpl** [comment]
@peterjaap thanks for the report. We will check it. 

However as far as I see those changes you pointed won't introduce security issues as in details.html as far as I check they just inform developers that output is unsanitized html by adding UnsanitizedHtml suffix 
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/xss-protection.html#knockout-templates

Anyway we will take look into that so we can keep alpaca as much compatible and secure as it can be with latest Magento version.

**Comment by Januszpl** [comment]
Internel ticket: DEV-71675

**Comment by anqaka** [comment]
theme updated for Magento 2.4.2
