### ISSUE TITLE
Magento 2.4.1 changes

### ISSUE THREAD

**Issue by santibm** [SnowdogApps/magento2-alpaca-theme#327]
Until now I've found those issues, I will update this with any other I find

File: `Magento_Checkout/web/js/sidebar-mixin.js`
Uses a method that doesn't exist anymore: `this._isOverflowed();` 

File: `Magento_Checkout/web/template/minicart/content.html`
Uses a method that doesn't exist anymore: `closeSidebar()`

**Comment by JKrupinski** [comment]
thanks, we are working on it
