### ISSUE TITLE
Composer module name

### ISSUE THREAD

**Issue by bsdnomad** [SnowdogApps/magento2-alpaca-theme#357]
Hi there,

README states the install command is:

`composer require snowdog/alpaca-packages`

but that is causing an error:

`[InvalidArgumentException]                                                                                                                                                                 
  Could not find a matching version of package snowdog/alpaca-packages. Check the package spelling, your version constraint and that the package is available in a stability which matches   
  your minimum-stability (stable).`

Proper composer command should be updated like:
`composer require snowdog/module-alpaca-packages`

**Comment by ofrankowska** [comment]
Hi, it's already fixed [here](https://github.com/SnowdogApps/magento2-alpaca-theme/pull/353/commits/4ac8e70f6c04f02eab6dbd0f7c3c81d602583e24) and will be featured in the next release. Thanks for the report.

**Comment by bsdnomad** [comment]
Thanks, @ofrankowska, for the prompt reaction! I hope that would save some headbanging to the other guys trying to install the theme.

Best,
K.
