### ISSUE TITLE
Help installing theme

### ISSUE THREAD

**Issue by pedrcruz** [SnowdogApps/magento2-alpaca-theme#370]
Hello guys,

I'm new to magento2, and i'm trying to put this theme working.
I already installed the theme but i think i'm missing the css, 
I need some insight how to the css works in this theme, if you guys could help me.

I will post a picture of what happen when i activate the theme.

Thanks!

![image](https://user-images.githubusercontent.com/19480484/108649893-2d6e3800-74b6-11eb-8097-c8a1baa3fdd4.png)

**Comment by anqaka** [comment]
Hi @pedrcruz !
Styles are generated with [snowdog/frontools](https://github.com/SnowdogApps/magento2-frontools) module. 
To make it work, you need to run `yarn` (or `npm install`) to install dependencies and run `setup` task which set a config file in `<magento-projetc>/dev/tools/frontools/config/themes.json` 
For alpaca theme config should look like this:
```
{
  "alpaca": {
    "src": "vendor/snowdog/theme-frontend-alpaca",
    "dest": "pub/static/frontend/Snowdog/alpaca",
    "locale": ["en_US"],
    "ignore": [
      "**/node_modules/**",
      "**/Snowdog_Components/docs/**",
      "**/Snowdog_Components/build/**"
    ]
  }
}
```
to compile styles, run `yarn styles && yarn babel && yarn svg` in `<magento-project>/tools` or directly in frontools: `<magento-project>/vendor/snowdog/frontools`

To setup child theme based on alpaca, please check our guide in [Alpaca README](https://github.com/SnowdogApps/magento2-alpaca-theme/blob/master/README.md)

**Comment by atishgoswami** [comment]
Hey @anqaka,

Thanks for the steps provided, I was able to the setup the theme properly 😃 

But getting an issue with the top menu / megamenu not appearing

![image](https://user-images.githubusercontent.com/2647377/121791308-40904980-cc06-11eb-9d57-0a7ff0fec500.png)

Is there any settings that need to happen or am I doing something wrong

Regards,
Atish

**Comment by memen45** [comment]
Same issue as OP, but was not solved by installing npm and running the `npm install`, `npm run setup`, `npm run styles && npm run babel && npm run svg`.

**Comment by ggm-dev** [comment]
Hi @atishgoswami  - Were you able to get menus working?   Any advice would be appreciated.  Thanks!

David

**Comment by ggm-dev** [comment]
In case it helps anyone else - I guess I needed to read a bit further down in the READme:-(. 

Menu - to display menu use Snowdog's magento2-menu module

Desktop menu:
identifier: main-desktop
Menu Main CSS Class: mega-menu
Mobile menu:
identifier: main-mobile
Menu Main CSS Class: dropdown-list
Footer links menu
identifier: main-footer
Menu Main Class: dropdown-list

**Comment by VivekShingala** [comment]
Hi @ggm-dev 

How do we import these menus which are mentioned in the README file? We tried creating a new desktop menu, but doesn't seem to work.

```
Desktop menu:
identifier: main-desktop
Menu Main CSS Class: mega-menu
```

**Comment by ggm-dev** [comment]
Here's what I did for desktop nav with magento sample data and it worked great. 

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/66025527/129390382-d484955a-2ba5-4eae-8b19-989a602d3557.png">

**Comment by VivekShingala** [comment]
Hi @ggm-dev 

+1 for your response.

Setting the store view to Default Store View instead of All Store Views worked!

**Comment by pedrcruz** [comment]
Hi guys, 
Sorry for the late response.
@ggm-dev responses did the trick for me.

Thanks all for the help.

You can close it now.
