### ISSUE TITLE
Child theme static-content:deploy

### ISSUE THREAD

**Issue by jakubcichocki** [SnowdogApps/magento2-alpaca-theme#383]
Hello,

we have problem with register child theme of aplaca. 

static-content:deploy command returns many errors

Compilation from source `vendor/snowdog/theme-frontend-alpaca/Magento_Theme/web/js/mixins/gallery-mixin.js` failed

```
Magento\Framework\View\Asset\File\NotFoundException: Unable to resolve the source file for 'frontend/cogitech/theme-frontend-cogitech/pl_PL/Magento_Theme/js/mixins/messages-mixin.js` in vendor/magento/framework/View/Asset/File.php:160`
```

this file is  exist in filesystem
```
ls vendor/snowdog/theme-frontend-alpaca/Magento_Theme/web/js/mixins/gallery-mixin.js
vendor/snowdog/theme-frontend-alpaca/Magento_Theme/web/js/mixins/gallery-mixin.js
```

my 
`vendor/cogitech/theme-frontend-cogitech/composer.json`
```
{
  "name": "cogitech/theme-frontend-cogitech",
  "description": "Child frontend cogitech theme form alpaca",
  "type": "magento2-theme",
  "require": {
    "snowdog/theme-frontend-alpaca": "*",
    "cogitech/module-cogitech-frontools": "*"
  },
  "autoload": {
    "files": [
      "registration.php"
    ]
  }
}
```

I already done:
- clear cache, flush cache
- yarn, yarn setup in frontools
- Remove empty folders

I will be grateful for your help.

**Comment by ggm-dev** [comment]
Hi @jakubcichocki  - were you able to resolve this issue?  I'm also having problems creating child theme - documentation is very unclear.  Great theme and amazing of snowdog team to share it, but it seems that GitHub issues are not attended to.

**Comment by ofrankowska** [comment]
Closing the issue due to inactivity
