### ISSUE TITLE
Missing something

### ISSUE THREAD

**Issue by ebgreen** [SnowdogApps/magento2-alpaca-theme#387]
Category grid views not working correctly.
contact bar missing.

Js error on load. May be all related.

Uncaught TypeError: base is not a constructor
    widget jQuery
    <anonymous> https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/Magento_Checkout/js/sidebar-mixin.js:11
    applyMixins https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/mage/requirejs/mixins.js:105
    applyMixins https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/mage/requirejs/mixins.js:104
    load https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/mage/requirejs/mixins.js:129
    execCb https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:1650
    check https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:866
    enable https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:1113
    bind https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:132
    emit https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:1156
    each https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:57
    emit https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:1155
    check https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:917
    enable https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:1113
    bind https://msl.magento2.local/static/version1618614633/frontend/MSL/MSL/en_US/requirejs/require.js:132
...

II see references to cms so maybe some of it I need to add some cms blocks?

**Comment by ebgreen** [comment]
Very odd that the contact bar and list.phtml file is not being applied when others are.

<img width="1680" alt="Screen Shot 2021-04-20 at 7 47 26 PM" src="https://user-images.githubusercontent.com/9063039/115489654-65250200-a211-11eb-86e0-c81d8b005953.png">

**Comment by ebgreen** [comment]
I even tried moving list.phtml to the child theme I made.  It does not work if I don't use a child theme and just use alpaca alone also

**Comment by ebgreen** [comment]
So after much fiddling and nothing changing I go on my dev box today and the grid is now loading right and the js error is gone. So not sure what was up with that.  I now think the other issues are just config-related and I'm missing something for the contact bar to still not. Maybe a cms block or something as I mentioned before.

**Comment by ofrankowska** [comment]
Hi, I think you're right. There are some CMS blocks missing. Here's a list with examples:
* header-contact-links
```html
<ul class="list contact-bar__list">
<li class="list-item contact-bar__item"><a class="contact-bar__link" href="/customer/account"><span class="button__text contact-bar__text">Account</span></a></li>
<li class="list-item contact-bar__item"><a class="contact-bar__link" href="/blog"><span class="button__text contact-bar__text">Blog</span></a></li>
<li class="list-item contact-bar__item"><a class="contact-bar__link" href="/contact"><span class="button__text contact-bar__text">Contact</span></a></li>
</ul>
<ul class="list contact-bar__list contact-bar__list--icons">
<li class="list-item contact-bar__item"><a class="contact-bar__link" href="tel:8001234567"> <span class="contact-bar__icon" aria-label=""> {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/svg-icon.phtml" icon="phone" title="Phone"}} </span> <span class="contact-bar__text"> Call us for free 800 - 123 - 4567 </span> </a></li>
<li class="contact-bar__item"><a class="contact-bar__link" href="mailto:test@test.com"> <span class="contact-bar__icon" aria-label=""> {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/svg-icon.phtml" icon="envelope" title="Email"}} </span> <span class="contact-bar__text"> Email Us </span> </a></li>
</ul>
```
* header-brief-info
```html
<div class="brief-info brief-info--link">
<ul class="list brief-info__items-container">
<li class="brief-info__list-item list__item"><a class="link button button--icon button--icon-light brief-info__link" href="/free-shipping"> <span class="brief-info__icon-wrapper"> {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/svg-icon.phtml" icon="delivery-truck" title="Free shipping icon" icon_class="brief-info__icon" role="presentation"}} </span> <span class="brief-info__title "> Free Shipping </span> <span class="brief-info__subtitle"> On Hundreds of Products </span> </a></li>
</ul>
</div>
```
* header-top-bar
`Subscribe and get 10$ for Shopping!`

**Comment by ebgreen** [comment]
Thanks a lot. I think I'm on the right track.


Thanks,


Eric Green

Pitbull Audio, CTO

Cell: (619) 985 - 1270

Email: ***@***.******@***.***
***@***.***>
