### ISSUE TITLE
Need some help installing

### ISSUE THREAD

**Issue by JR2Media** [SnowdogApps/magento2-alpaca-theme#402]
I'm a little stuck on installing. I'm following the instructions, but I have a couple of questions.

1. `Create child theme composer repository`, does this mean create a regular Magento theme, i.e under `app/design/frontend/vendor/theme`?

2. Does this `"name": "vendor/theme-frontend-child-theme"` have to be like `mycompany/my-theme`?

3. `Create separate module with frontools configuration (it should be required in theme composer dependencies)`, save as `1.`, does this mean to create a regular magento module?

4. `composer require vendor/theme-frontend-child-theme`, so I should run `composer require mycompany/my-theme`? If so, where do I run `composer` from? From the root magento directory where it's `composer.json` is? Or from the `theme`, or `module` directory?

I'm confused because how does running `composer require` know where the module, and theme, is?

Cheers.

**Comment by oliwerhelsen** [comment]
@JR2Media did you got this answers? I am confused about the same :-)

**Comment by hershkoy** [comment]
Me too :(

**Comment by ggm-dev** [comment]
Hi @JR2Media  - Would love to hear how your resolved this.  Having similar issues here.  

David

**Comment by JamesTheHacker** [comment]
I'm not sure if I solve this issue because I closed it. But, I rarely close without an answer. I gave up with this theme in the end. I'll setup a development store and see if I can resolve this.
