### ISSUE TITLE
Broken rendering of requisition list item page

### ISSUE THREAD

**Issue by daanvdberg** [SnowdogApps/magento2-alpaca-theme#419]
Hello Snowdog,

First time here, so hopefully this provides enough info for you guys.

While working on the requisition list section I came upon a rendering problem when trying to access the list detail view: **requisition_list/requisition/view/requisition_id/#/**

After some investigating, it appears one of the translation functions is missing its second underscore.

Line in question:
https://github.com/SnowdogApps/magento2-alpaca-theme/blob/0aaf110fc9c88d8ebb6b43acc21c1dd03362ebf4/Magento_RequisitionList/templates/requisition/view/items/item.phtml#L170

Thanks for the awesome work.

**Comment by ofrankowska** [comment]
Hi, thanks for reposting the issue.
