### ISSUE TITLE
No alive nodes found in your cluster. Maybe issue with Smile module?

### ISSUE THREAD

**Issue by hershkoy** [SnowdogApps/magento2-alpaca-theme#424]
Hi. Just letting you know that I run into a bug when installing the theme with Magento 2.4.2. 
It seems like a bug in elasticsuite, I reported it in [their repo](https://github.com/Smile-SA/elasticsuite/issues/2180)

**Comment by JKrupinski** [comment]
Hi, try to reinstall elasticsearch plugins

on linux
```
sudo -i

cd /usr/share/elasticsearch && bin/elasticsearch-plugin remove analysis-phonetic && bin/elasticsearch-plugin install analysis-phonetic && bin/elasticsearch-plugin remove analysis-icu && bin/elasticsearch-plugin install analysis-icu

service elasticsearch restart
```
