### ISSUE TITLE
Compilation from source: LESS file is empty: frontend/Vendor/theme/en_GB/css/critical.less

### ISSUE THREAD

**Issue by andyt** [SnowdogApps/magento2-alpaca-theme#545]
I've followed instructions and have my child theme as a composer module, but I'm receiving this message:

1 exception(s):
Exception #0 (Magento\Framework\View\Asset\ContentProcessorException): Compilation from source: LESS file is empty: frontend/Vendor/theme/en_GB/css/critical.less

Any assistance appreciated.

Andy

**Comment by andyt** [comment]
Fixed - this was due to en_US locale config in config/themes.json.

**Comment by passtet** [comment]
@andyt how did you resolve the issue? I cannot even start a basic theme "alpaca" due to this error..

**Comment by ofrankowska** [comment]
Hi @passtet, please check your frontools configration (`theme.json`) and make sure you have styles compiled (`yarn styles`).
You can read about this in our new docs:
https://magento2-alpaca-docs.vercel.app/guide/getting-started/alpaca-setup-guide.html#set-up-alpaca-manually
https://magento2-alpaca-docs.vercel.app/guide/working-with-alpaca/frontools.html

If you need any more help, please let me know! :)

**Comment by CYANIDE-7** [comment]
> Hi @passtet, please check your frontools configration (`theme.json`) and make sure you have styles compiled (`yarn styles`). You can read about this in our new docs: https://magento2-alpaca-docs.vercel.app/guide/getting-started/alpaca-setup-guide.html#set-up-alpaca-manually https://magento2-alpaca-docs.vercel.app/guide/working-with-alpaca/frontools.html
> 
> If you need any more help, please let me know! :)

![Screenshot 2022-07-27 174030](https://user-images.githubusercontent.com/79502752/181243641-35c15d85-22c6-4953-93f9-b797232b8635.png)
I am facing the same issue, in source file css file is not getting generated and I have  followed the proper guide for setting up frontools  could you please help me with it

**Comment by JKrupinski** [comment]
> > Hi @passtet, please check your frontools configration (`theme.json`) and make sure you have styles compiled (`yarn styles`). You can read about this in our new docs: https://magento2-alpaca-docs.vercel.app/guide/getting-started/alpaca-setup-guide.html#set-up-alpaca-manually https://magento2-alpaca-docs.vercel.app/guide/working-with-alpaca/frontools.html
> > If you need any more help, please let me know! :)
> 
> ![Screenshot 2022-07-27 174030](https://user-images.githubusercontent.com/79502752/181243641-35c15d85-22c6-4953-93f9-b797232b8635.png) I am facing the same issue, in source file critical.less file is not getting generated and I have followed the proper guide for setting up frontools could you please help me with it

@CYANIDE-7 
From root magento directory run:
```cd tools && yarn styles && yarn svg```
