### ISSUE TITLE
Javascript files on front-end.

### ISSUE THREAD

**Issue by Adwait21** [SnowdogApps/magento2-alpaca-theme#563]
Hello @Igloczek ,

We are facing an issue related to the Javascript files on the front-end. Alpaca theme setup is complete on Magento 2 local instance with PHP 8.1 and Composer 2.x.
We are able to edit the Magento layout and templates files as well as SASS files and the changes are reflected on the front-end. But the JS files are not loading properly.
Eg. - The JS file for the side-menu is loading on the front-end leading to the issue of 'Mobile Menu' not working properly. Upon clicking the hamburger icon, side-menu modal is not displayed.

**Comment by Igloczek** [comment]
Hi, did you run `babel` task from Frontools?

**Comment by Igloczek** [comment]
@ofrankowska please take it over

**Comment by Adwait21** [comment]
Hi,

It seems we missed some of the steps during our initial setup of the Alpaca theme. We created new instance and followed the steps accurately and now all the JS files are loading on the front-end.

Thank you for your help @Igloczek .
