### ISSUE TITLE
Disabling 'Elasticsuite' and using default or some other search module

### ISSUE THREAD

**Issue by Adwait21** [SnowdogApps/magento2-alpaca-theme#565]
Hello @ofrankowska @Igloczek ,

We wish to use either the default 'ElasticSearch' of the Magento or some other module for the search functionality.

So for this we tried two different scenarios -
1. Keep all of the Smile_ElasticSuite modules enabled and switch to ElasticSearch7 from the admin backend. This leads to the 'Instance of' error (PFA - Error 2).
2. Disable all the Smile_ElasticSuite modules and then switch to the ElasticSearch7 from the admin backend. This leads to the 'Illegal state' error (PFA - Error 1).

Thus, we wanted to know if there is a way to disable the ElasticSuite and use default ElasticSearch7 or some other extension?

Thank you.
![Error - 1](https://user-images.githubusercontent.com/86280863/179150968-c67a39ee-de96-429e-a221-52f5dfdbf8a3.png)
![Error - 2](https://user-images.githubusercontent.com/86280863/179150974-5df42921-d152-4290-a052-e1869243b010.png)

**Comment by adamwaclawczyk** [comment]
2. Should be the standard procedure for disabling ElasticSuite modules, we have tested this locally and confirm it's working as intended. 
The steps to disable all Smile_Elasticsuite modules on 2.4.3
```
php bin/magento module:disable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteCatalogGraphQl Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker Smile_ElasticsuiteThesaurus Smile_ElasticsuiteSwatches Smile_ElasticsuiteIndices Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteAdminNotification Smile_ElasticsuiteAnalytics
rm -rf generated/code
bin/magento setup:upgrade
bin/magento cache:flush
bin/magento indexer:reindex
```
I think the Illegal state error means that somewhere in code must be a call to addFieldToFilter on collection that already has searchResult resolved. Does the error still occur after setup:upgrade/setup:static-content:deploy/cache:clean?
