### ISSUE TITLE
2.4.6 Error: Class "Zend_Json" not found

### ISSUE THREAD

**Issue by 101Luuk** [SnowdogApps/magento2-alpaca-theme#579]
Hi,

When i upgraded to 2.4.6 i got the following error:

window.checkout = Error: Class "Zend_Json" not found in ../vendor/snowdog/theme-frontend-alpaca/Magento_Theme/templates/header/minicart.phtml:111

Zend usage is deprecated since 2.4.6. To fix this you need to replace `Zend_Json` with` \Laminas\Json\Json`

**Comment by JKrupinski** [comment]
Hi @101Luuk It will be fixed in 2.28.3 release
