### ISSUE TITLE
Doumentation

### ISSUE THREAD

**Issue by WouterSteen** [SnowdogApps/magento2-alpaca-theme#94]
Hey Guys,

i'm planning to use the alpace theme as base theme for some of our projects.
This is looking very good.

Few questions tho, is there some documentation available how to set this up in magento 2?
Problems/questions I have now are:
- how this styles.css rendered and copied to the static folder?
- I dont see a link between the theme and alpaca components? How does this work?
- Whats the recommended way to edit files?
- How are static files from alpaca components placed in the magento static folder?
I'm missing something right?

Cheers,

**Comment by Igloczek** [comment]
Hi Wouter!
Thank for kind words and great questions.
I'm planning to add docs/tutorials stuff this week and release it as 1.0 next week, so please wait a while.

**Comment by Igloczek** [comment]
@WouterSteen Docs landed with v1.0.0.
Let me know if everything is now clear or we need to work on it a bit more :)

**Comment by WouterSteen** [comment]
Thanks! This will do!

We will look into it later this week!

**Comment by Jdeezy** [comment]
Just to confirm, we're good to start using this base theme for projects now? It looks awesome!

**Comment by Igloczek** [comment]
@Jdeezy Yep, it works.
We are already live with one store based on this theme and M2.3 - https://fashinary.com/

**Comment by Jdeezy** [comment]
Damn, ok.I'll keep an eye on the main page for info about 2.3, thanks for the update ;)
